sudo: required
services:
  - docker

before_install:
  - docker build -t vmaldosan/dockerised-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vmaldosan/dockerised-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "dockerised-app"
  env: "DockerisedApp-env"
  bucket_name: "elasticbeanstalk-eu-west-1-538312665280"
  bucket_path: "dockerised-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
